name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/${{ github.repository_owner }} > stats.json
          followers=$(jq '.followers' stats.json)
          views=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }} | jq '.views')
          sed -i "s|<!-- FOLLOWERS -->|$followers|g" README.md
          sed -i "s|<!-- VIEWS -->|$views|g" README.md
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Update README with GitHub stats'
          git push
